import axios from 'axios';
import { Keypair, PublicKey, Connection } from '@solana/web3.js';
import { getAssociatedTokenAddress } from '@solana/spl-token';
import bs58 from 'bs58';
import 'dotenv/config';

/**
 * Script to create an ICO by calling the local API
 *
 * ICO Flow:
 * 1. ESCROW (auto-generated by API) - Holds all tokens for sale initially
 * 2. VAULT (your ATA) - Receives 50% of purchased tokens for staking
 * 3. During purchase:
 *    - User sends SOL to escrow
 *    - 50% of tokens transfer from escrow → vault (for staking)
 *    - 50% stays in escrow (user claims later)
 */

async function createICO() {
  // Configuration
  const API_URL = process.env.API_URL || 'http://localhost:6770';
  const PAYER_PRIVATE_KEY = process.env.PAYER_PRIVATE_KEY;
  const RPC_URL = process.env.RPC_URL;

  // Validate required env vars
  if (!PAYER_PRIVATE_KEY) {
    console.error('✗ Error: PAYER_PRIVATE_KEY environment variable is required');
    console.error('Usage: PAYER_PRIVATE_KEY=<base58-private-key> tsx create-ico.ts');
    process.exit(1);
  }

  if (!RPC_URL) {
    console.error('✗ Error: RPC_URL environment variable is required');
    process.exit(1);
  }

  // Create keypair from private key
  const payerKeypair = Keypair.fromSecretKey(bs58.decode(PAYER_PRIVATE_KEY));
  const PAYER_PUBLIC_KEY = payerKeypair.publicKey.toBase58();

  // ICO configuration - customize these values
  const TOKEN_ADDRESS = process.env.TOKEN_ADDRESS; // Existing token mint address
  const TOKEN_METADATA_URL = process.env.TOKEN_METADATA_URL;
  const TOTAL_TOKENS_FOR_SALE = process.env.TOTAL_TOKENS_FOR_SALE || '8000000000'; // 8k tokens with 6 decimals
  const TOKEN_PRICE_SOL = process.env.TOKEN_PRICE_SOL || '0.0001'; // Price per token in SOL
  const TREASURY_WALLET = process.env.TREASURY_WALLET || PAYER_PUBLIC_KEY;
  const TREASURY_SOL_AMOUNT = process.env.TREASURY_SOL_AMOUNT || '400000000'; // .4 SOL in lamports
  const VAULT_OWNER = process.env.VAULT_OWNER; // Optional: specific wallet to own the vault

  console.log('Creating ICO Sale');
  console.log('================');
  console.log(`API URL: ${API_URL}`);
  console.log(`Creator: ${PAYER_PUBLIC_KEY}`);
  console.log(`Token Address: ${TOKEN_ADDRESS || 'Not provided - you must create a token first'}`);
  console.log(`Tokens for Sale: ${TOTAL_TOKENS_FOR_SALE}`);
  console.log(`Price per Token: ${TOKEN_PRICE_SOL} SOL`);
  console.log(`Treasury Wallet: ${TREASURY_WALLET}`);
  console.log();

  if (!TOKEN_ADDRESS || !TOKEN_METADATA_URL) {
    console.error('✗ Error: TOKEN_ADDRESS and TOKEN_METADATA_URL must be provided');
    console.error('Please set these environment variables:');
    console.error('  TOKEN_ADDRESS - The SPL token mint address');
    console.error('  TOKEN_METADATA_URL - The metadata URL for the token');
    process.exit(1);
  }

  try {
    // Step 1: Set up vault token account (for receiving 50% of purchased tokens for staking)
    console.log('Step 1: Setting up vault token account...');
    const connection = new Connection(RPC_URL, 'confirmed');
    const tokenMint = new PublicKey(TOKEN_ADDRESS);

    let vaultTokenAccount: PublicKey;
    let vaultKeypair: Keypair | null = null;

    if (VAULT_OWNER) {
      // Use specified vault owner's ATA
      const vaultOwnerPubkey = new PublicKey(VAULT_OWNER);
      vaultTokenAccount = await getAssociatedTokenAddress(
        tokenMint,
        vaultOwnerPubkey
      );
      console.log(`✓ Using provided vault owner: ${VAULT_OWNER}`);
      console.log(`  Vault token account: ${vaultTokenAccount.toString()}`);
    } else {
      // Generate a new keypair for the vault (separate from creator)
      vaultKeypair = Keypair.generate();
      vaultTokenAccount = await getAssociatedTokenAddress(
        tokenMint,
        vaultKeypair.publicKey
      );
      console.log(`✓ Generated new vault keypair`);
      console.log(`  Vault owner: ${vaultKeypair.publicKey.toBase58()}`);
      console.log(`  Vault token account: ${vaultTokenAccount.toString()}`);
      console.log(`  Vault private key: ${bs58.encode(vaultKeypair.secretKey)}`);
      console.log(`  ⚠️  SAVE THIS PRIVATE KEY - You'll need it to access vault tokens!`);
    }

    // Step 2: Call /ico/create endpoint
    console.log('\nStep 2: Creating ICO sale...');
    const icoData = {
      tokenAddress: TOKEN_ADDRESS,
      creatorWallet: PAYER_PUBLIC_KEY,
      tokenMetadataUrl: TOKEN_METADATA_URL,
      totalTokensForSale: TOTAL_TOKENS_FOR_SALE,
      tokenPriceSol: TOKEN_PRICE_SOL,
      vaultTokenAccount: vaultTokenAccount.toString(),
      treasuryWallet: TREASURY_WALLET,
      treasurySolAmount: TREASURY_SOL_AMOUNT,
    };

    const createResponse = await axios.post(`${API_URL}/ico/create`, icoData);

    console.log('\nICO creation response:');
    console.log(JSON.stringify(createResponse.data, null, 2));

    if (createResponse.data.success) {
      const escrowPubKey = createResponse.data.icoSale.escrow_pub_key;

      console.log('\n✓ ICO sale created successfully!');
      console.log(`Token Address: ${TOKEN_ADDRESS}`);
      console.log(`Vault (your ATA): ${vaultTokenAccount.toString()}`);
      console.log(`Escrow Public Key: ${escrowPubKey}`);

      // Calculate escrow's token account
      const escrowTokenAccount = await getAssociatedTokenAddress(
        tokenMint,
        new PublicKey(escrowPubKey)
      );

      console.log(`\nNext steps:`);
      console.log(`1. Transfer ${TOTAL_TOKENS_FOR_SALE} tokens to ESCROW token account:`);
      console.log(`   Escrow Token Account: ${escrowTokenAccount.toString()}`);
      console.log(`   (50% will go to vault during purchases, 50% held for user claims)`);
      console.log(`2. Users can purchase tokens using: POST /ico/${TOKEN_ADDRESS}/purchase/prepare`);
    }

  } catch (error: any) {
    console.error('\n✗ Error occurred:');
    if (error.response) {
      console.error(`Status: ${error.response.status}`);
      console.error(`Error: ${JSON.stringify(error.response.data, null, 2)}`);
    } else if (error.request) {
      console.error('No response received from server');
      console.error(error.message);
    } else {
      console.error(error.message);
    }
    process.exit(1);
  }
}

// Run the script
createICO();
